#29 enabled static website hosting, uploaded index and error file via terraform (#30)

diff --git a/bin/set_tf_alias b/bin/set_tf_alias
--- a/bin/set_tf_alias
+++ b/bin/set_tf_alias
@@ -1,18 +1,17 @@
 #!/usr/bin/env bash
 
-# Define the alias you want to add
-alias tf="terraform"
+# Check if the alias already exists in the .bash_profile
+grep -q 'alias tf="terraform"' ~/.bash_profile
 
-# Check if .bash_profile exists and append the alias if it does
-if [ -f ~/.bash_profile ]; then
-    echo "alias tf='terraform'" >> ~/.bash_profile
-    echo "Alias 'tf' for 'terraform' has been added to .bash_profile."
+# $? is a special variable in bash that holds the exit status of the last command executed
+if [ $? -ne 0 ]; then
+    # If the alias does not exist, append it
+    echo 'alias tf="terraform"' >> ~/.bash_profile
+    echo "Alias added successfully."
 else
-    # If .bash_profile doesn't exist, create it and add the alias
-    touch ~/.bash_profile
-    echo "alias tf='terraform'" >> ~/.bash_profile
-    echo "Created .bash_profile and added the alias 'tf' for 'terraform'."
+    # Inform the user if the alias already exists
+    echo "Alias already exists in .bash_profile."
 fi
 
-# Activate the changes in the current shell session
+# Optional: source the .bash_profile to make the alias available immediately
 source ~/.bash_profile
